name: eatrev
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+3
  path_provider: ^2.0.14
  fluttertoast: ^8.2.6
  image: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sushi.jpg
    - assets/images/pizza.jpg
    - assets/images/man_6.png
    - assets/images/man_7.png
